### ISSUE TITLE
Support for polylines

### ISSUE THREAD

**Issue by alexcroox** [brandoncopeland/Leaflet.boundsAwareLayerGroup#3]
Does this work for polylines, especially those that might extend past the current bounds?

**Comment by brandoncopeland** [comment]
Yes. Any marker or vector layer implementing `getLatLng` or `getBounds` is supported. This includes polylines.

Essentially, each map `moveend` triggers a bounds check. When checking bounds, `getBounds` is called for each polyline. If the resulting bounds intersects the current map bounds, the feature is added to the map. If the bounds do not intersect, the feature is removed from the map.
